GET http://localhost:30303/api/v1/certification/enum/activities HTTP/1.1

###

GET http://localhost:30303/api/v1/certification/enum/regions HTTP/1.1

###

GET http://localhost:30303/api/v1/certification/enum/colors HTTP/1.1

###

GET http://localhost:30303/api/v1/certification/enum/certification_types HTTP/1.1

###

POST http://localhost:30303/api/v1/certification/canDo HTTP/1.1
content-type: application/json

{
    "greenpass": "{\"tipo_certificazione\":\"4\"}",
    "activity": "MEZZI_PUBBLICI",
    "region": "BASILICATA"
}

### INFURA

POST http://localhost:30303/api/v1/certification/emit HTTP/1.1
Content-Type: application/json

{
    "greenpass": "julia",
    "certificationType": "VACCINO1",
    "privateKey": "0x982cf7b3e27963192e466f7c023a1f8dad241468b0818ac33e006dcebf22f3db"
}

###
# GANACHE

POST http://localhost:30303/api/v1/certification/emit HTTP/1.1
Content-Type: application/json

{
    "greenpass": "ciccio",
    "certificationType": "VACCINO1",
    "privateKey": "df11e9aee4583d93331e3d375a60cf54e54533822b34561fa4301a6297af3f81"
}

###
#GANACHE
POST http://localhost:30303/api/v1/privileges/grat/certification_minter_role HTTP/1.1
Content-Type: application/json

{
    "to": "0x8920d231Fd5a5E95707ce7e2f1288294E81c4B7c",
    "privateKey": "df11e9aee4583d93331e3d375a60cf54e54533822b34561fa4301a6297af3f81"
}
###

POST http://localhost:30303/api/v1/certification/emitPublic HTTP/1.1
Content-Type: application/json

{
    "greenpass": "ciccio",
    "certificationType": "1",
    "pubKey": "0x7b512483Aff3e71b77D023b8816eb3d7DdAF9951"
}