GET http://localhost:30303/api/v1/certification/enum/activities HTTP/1.1

###

GET http://localhost:30303/api/v1/certification/enum/regions HTTP/1.1

###

GET http://localhost:30303/api/v1/certification/enum/colors HTTP/1.1

###

GET http://localhost:30303/api/v1/certification/enum/certification_types HTTP/1.1

###

POST http://localhost:30303/api/v1/certification/canDo HTTP/1.1
content-type: application/json

{
    "greenpass": "michele",
    "activity": "BAR_E_RISTORANTI",
    "region": "MARCHE"
}

###

POST http://localhost:30303/api/v1/certification/emit HTTP/1.1
Content-Type: application/json

{
    "greenpass": "ciccio",
    "certificationType": "VACCINO1",
    "privateKey": "cd4fa644e7b22d964436169abf37bc3a0cbadf91a716c56454948ac0f0d1916d"
}